Pop up using Javascript #PR
Sonikak004/my-portfolio pull request #11
Opened 2023-02-10 09:33 UTC by Sonikak004

### In this Branch I have 👍 

- when button to check project details is clicked, the popup with details about the project appears ✔️ 
- when the close (X) button is clicked,, the popup disappears. ✔️ 
- used JavaScript array of objects to store all of the information for all projects ✔️ 
   - name, description, featured image, technologies, link to live, link to source 👍 
- updated the main page so that the projects section is created dynamically 💯 
-  implemented the popup window 👍 
- No linter Errors ✅

2023-02-10 11:29 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] has Microverse template logo which has been to be removed and replace with student personal logo if he or she has one. Kindly remove the Microverse logo and replate it with your logo or leave empty.
- [ ] The link to the MIT license is broken, kindly fix that too by following this [article](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to properly set it up for your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-10 13:08 UTC, emmiiorji requested changes
Hi @Sonikak004, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![BbcanBbcan3GIF](https://user-images.githubusercontent.com/20554583/218099442-c28b4fb1-69ab-4a2b-a3da-934f60d5ca46.gif)


## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Good use of GitHub flow


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 13:08 UTC, emmiiorji commented on index.html
> +     </div>
[Optional] Well done for rendering the projects dynamically from JavaScript. As given on the figma design, on desktop version, the project cards look a little different. The card without the "See Project" button shows how the cards would display normally. However, the card having the "See Project" button shows how the cards display when hovered.

Normal project card:
![image](https://user-images.githubusercontent.com/20554583/218098854-696459d1-15e6-418d-aee9-2c775e278d37.png)

Project card when hovered:
![image](https://user-images.githubusercontent.com/20554583/218098880-435cda05-11bc-4e36-a991-ac9b2d17bf71.png)

2023-02-10 13:08 UTC, emmiiorji commented on index.html
> +          <button class="button3" type="button">
[Optional] The website seems to have a horizontal scroll. For a better user experience, I think you should avoid having a horizontal scroll.

![image](https://user-images.githubusercontent.com/20554583/218099336-ede0724b-8078-45a8-89d5-b1604535a304.png)

2023-02-10 15:22 UTC, GzimAsani requested changes
### Hello @Sonikak004                 :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with fixing the mobile version as the previous reviewer requested :+1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._









 ### Hello @developertariq                :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with the redux and styling :+1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 15:22 UTC, GzimAsani commented on index.js
> +  },
- [ ] You have a lot of repetition on your CSS file, and this falls under the category of bad CSS practice. For example, you have used display:flex 46 times. I would suggest you create a class d-flex and use display:flex there and use on your HTML whenever you need. Also make sure to take into the account the previous reviewer's request based on css repetition regarding to ptext 1,2,3,4 etx
![image](https://user-images.githubusercontent.com/62705947/218128383-859ecf6d-b17b-4b05-b9f3-35ce55501f5f.png)

2023-02-11 08:27 UTC, Deepakdanger approved these changes
Hi @Sonikak004, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 08:37 UTC, merged