Add Desktop version
Sonikak004/my-portfolio pull request #6
Opened 2023-01-21 17:41 UTC by Sonikak004

### In this Branch I have : 💯 

- Used **_HTML_** to create Desktop version 👍 
- Used **_CSS_** to style the Desktop Version ✅   
- Used _Media Queries_ 😄 
- Linter Checked ✔️ 

`Tried to Replicate Figma Template 😜 `

2023-01-21 20:53 UTC, Kossi-stack requested changes
## Hi @Sonikak004,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

- [ ] Kindly fix your twitter social handle.

 _Check the comments under the review for more changes_.

## Optional suggestions

 - [OPTIONAL] Kindly edit the PR's title to something more descriptive. it can be " Portfolio: Desktop version  PR".

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-21 20:53 UTC, Kossi-stack commented on style.css
> +  .nav-icon {
- [ ] Kindly make the background image of the header width 100%
- [ ] Your Design
<img width="1440" alt="Screenshot 2023-01-21 at 12 28 04" src="https://user-images.githubusercontent.com/81444338/213886219-8c23931e-2717-489a-b3f8-5b4a10655133.png">



- [ ] Figma
<img width="605" alt="Screenshot 2023-01-21 at 12 33 31" src="https://user-images.githubusercontent.com/81444338/213886146-3ed3629f-350f-49f0-b1c0-ebe8a7c244e8.png">

2023-01-21 20:53 UTC, Kossi-stack commented on style.css
> +    width: 100%;
- [ ] Kindly fix the background image 
- [ ] Your design
<img width="1440" alt="Screenshot 2023-01-21 at 12 38 25" src="https://user-images.githubusercontent.com/81444338/213886428-42a53ee7-9c52-464b-aadc-81fbcd1d8ac7.png">
- [ ] Figma
<img width="627" alt="Screenshot 2023-01-21 at 12 45 16" src="https://user-images.githubusercontent.com/81444338/213886512-58d50dee-a68c-4081-aa1c-97a3b3f6e32b.png">

2023-01-21 21:47 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Sonikak004 , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ].. ✅ Green linters
- [ ].. ✅ Good readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 21:47 UTC, joskalenda commented on style.css
> +  .nav-icon {
As requested by the previous reviewer, please make the necessary changes to match the original design, see this record below how your page behaves on both mobile and desktop version


![5](https://user-images.githubusercontent.com/77843050/213888062-5f773892-4734-487f-a211-7651e7a3cb42.gif)

2023-01-21 22:00 UTC, Sonikak004 commented on style.css
> +  .nav-icon {
![2023-01-21 (3)](https://user-images.githubusercontent.com/99942992/213888601-69a69dc4-cff0-4181-b04c-c930c7385b30.png)

2023-01-21 23:11 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @Sonikak004 

While you have done a good job implementing the project requirements. But there are few things that you still need to work on to complete this milestone. But I know you can easily conquer this one. Right ? 🎯😄
**_You are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Descriptive PR
- ✅ Good README file
- ✅ Correct Linters

However, there is always room for improvement.

## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

From [your latest commit](https://github.com/Sonikak004/my-portfolio/pull/6/commits/6026b9a1de2e8a5afc63f5911595feb6bb4efd7e) I can see that changes requested by previous reviewer are not implemented. No worries, let's implement them now 💪 You got this. Let's fix them so that we can move to the next milestone of the project. What do you say ? 🎯
_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 08:08 UTC, AlphaNtihinduka requested changes
## Hi @Sonikak004 🙋‍♂️

Good job working on your first contact form. You have done the design to the best expectation and incredibly well. 👏  

However, there are some issues mostly on the design practice.

You still need to implement few on the project but you are almost there!!! :watch: 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Optional suggestions
- [ ] [OPTIONAL] I have also noticed that you are using much of the `margins` in your portfolio. I applaud 👏 👏  you for the great effort to make the design look incredible. However, if not properly used it can be [harmful](https://news.ycombinator.com/item?id=22676442) and cause horizontal scrolls. Kindly verify the margins you used to ensure that they don't cause any harm to your portfolio.
- [ ] [OPTIONAL] The sections always adapt to 100$ width of the html, therefore unless the width of the html has been changed you may consider using width: 100% on sections. As you are fixing the horizontal scroll effects, Kindly consider verifying the widths and margins. Read more [here](https://polypane.app/blog/strategies-for-dealing-with-horizontal-overflows/) and [here](https://www.quora.com/Is-setting-negative-margins-in-CSS-to-be-considered-bad-practice)

Your portifolio demo

https://user-images.githubusercontent.com/99394374/215254604-f9acfe01-d464-4092-aa62-d3c300b59256.mp4


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-01-28 11:18 UTC, zieeco requested changes
Hi @Sonikak004 ,


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 11:18 UTC, zieeco commented on style.css
>    display: grid;
- Hey, you've really done a great job, however as pointed out by the previous reviewer, your mobile design is still having the horizontal scroll effect and it's so obvious that I can not overlook it to approve your project. Please, kindly see the image below to fix this issue. I tried using a screencast, but it misbehaving that's why i did the screenshot. :pray: 



![Screenshot from 2023-01-28 12-14-21](https://user-images.githubusercontent.com/59397159/215263550-d783dbd4-fae9-4072-b0db-daae6e1e0229.png)
![Screenshot from 2023-01-28 12-14-16](https://user-images.githubusercontent.com/59397159/215263552-a638ba36-62ce-41b4-8957-d6c04a1d821d.png)
![Screenshot from 2023-01-28 12-14-10](https://user-images.githubusercontent.com/59397159/215263554-c1e8d5fe-9937-4d85-b1a1-7785f534b9cc.png)
![Screenshot from 2023-01-28 12-14-05](https://user-images.githubusercontent.com/59397159/215263556-95ced9b9-daac-4e09-99f2-0e05ed316170.png)
![Screenshot from 2023-01-28 12-14-00](https://user-images.githubusercontent.com/59397159/215263558-31ddbcca-87ad-4bed-a178-41b56219c5b6.png)
![Screenshot from 2023-01-28 12-13-54](https://user-images.githubusercontent.com/59397159/215263559-0c7b582e-c98c-4097-99ea-18315ffa046a.png)
![Screenshot from 2023-01-28 12-13-47](https://user-images.githubusercontent.com/59397159/215263560-e4cdd67c-562f-4666-95f5-a37bced8484b.png)
![Screenshot from 2023-01-28 12-13-38](https://user-images.githubusercontent.com/59397159/215263561-b552f504-087f-41e1-8307-c0c2c3d501d6.png)
![Screenshot from 2023-01-28 12-13-00](https://user-images.githubusercontent.com/59397159/215263562-6ceb0516-9ff7-4d61-8e4c-22f97d512ff3.png)

2023-01-28 12:22 UTC, huseyinbiyik requested changes
Hi @Sonikak004,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝


 ## Required Changes ♻️
- Please you fixed the horizontal overflowing issue as the previous reviewer requested. Kindly check the GIF below.
![Screen Recording 2023-01-28 at 3 07 00 PM](https://user-images.githubusercontent.com/25887253/215266116-ccc3d7f6-7068-4f18-944f-a6d75fde4a7d.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 12:53 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅

## Hi @Sonikak004👋

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media3.giphy.com/media/l4JySAWfMaY7w88sU/giphy.gif"/>

## Highlights:
* Well-written PR description ✔️ 
* All tests passed ✔️ 

## Optional suggestions:

- [ ] Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" or "linters are added" ... etc 👍 


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-28 12:54 UTC, merged